### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/runtime-tools/runtimejs-kernels'

### ISSUE THREAD

**Issue by claudiopro** [runtimejs/helloworld#1]
Hi,
I'm having an issue running the `runtime-qemu ./initrd` command on Mac OS X 10.10. I assume I could work it around by running the command with `sudo`, but I wonder if this is expected?

``` bash
$ runtime-qemu ./initrd
shell.js: internal error
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/runtime-tools/runtimejs-kernels'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at /usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:65:10
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/common.js:186:23)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-prebuilt.js:8:11)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-runtime.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/runtime-tools/bin/runtime-qemu.js:63:1)
    at Module._compile (module.js:434:26)
```

Thanks!

**Comment by claudiopro** [comment]
I'm actually referring to the instructions provided in the [Medium article](https://medium.com/@iefserge/runtime-js-javascript-library-os-823ada1cc3c), this project runs fine with `npm start`. I guess it's a non-issue? :sweat:

**Comment by iefserge** [comment]
@claudiopro are you on Ubuntu?
yep, looks like global npm install directory has restricted access. Interesting that it works on OSX for me.

**Comment by iefserge** [comment]
Probably a good idea to use some `tmp` directory instead.

**Comment by iefserge** [comment]
Opened an issue https://github.com/runtimejs/runtime-tools/issues/5

**Comment by claudiopro** [comment]
@iefserge no, I'm on Mac OS X 10.10 as an Admin user.

**Comment by iefserge** [comment]
@claudiopro hm, maybe different npm version?

```
$ npm --version
2.13.5
```

**Comment by claudiopro** [comment]
I switched to node 4.0.1 and

``` bash
$ npm --version
2.14.3
```

Let me try switching back to `v4.0.0` via `nvm`.

**Comment by claudiopro** [comment]
Same issue with node v0.12.7 and npm v2.11.3 :-(

Further details:

``` bash
$ ls -l /usr/local/lib/node_modules
...
drwxr-xr-x  15 nobody  staff  510 Sep 22 18:40 runtime-tools

$ ls -l /usr/local/lib/node_modules/runtime-tools
total 88
-rw-r--r--  1 nobody  staff  11358 May  3 23:04 LICENSE
-rw-r--r--  1 nobody  staff    140 May 16 19:19 README.md
drwxr-xr-x  3 nobody  staff    102 Jul 26 22:07 bin
-rw-r--r--  1 nobody  staff    986 May 16 19:17 get-prebuilt.js
-rw-r--r--  1 nobody  staff    212 Jun 20 20:09 get-runtime.js
-rw-r--r--  1 nobody  staff    215 May 16 19:41 logs.js
drwxr-xr-x  8 nobody  staff    272 Sep 22 18:40 node_modules
-rw-r--r--  1 root    staff   1519 Sep 22 18:40 package.json
-rw-r--r--  1 nobody  staff   2485 Jul 26 22:07 qemu.js
-rw-r--r--  1 nobody  staff    441 May 16 14:30 raw-exec.js
-rw-r--r--  1 nobody  staff   1179 May 15 21:55 shell-exec.js
```

**Comment by facekapow** [comment]
This should be fixed with runtime-tools v2.0.0, which uses '~/.runtime' for the kernel download. @claudiopro Can you confirm it works?

**Comment by claudiopro** [comment]
@ArielAbreu lemme try...

**Comment by claudiopro** [comment]
Yes, it works now. Thanks!

``` sh
$ sudo npm update runtime-tools -g
Password:
/usr/local/bin/runtime-qemu -> /usr/local/lib/node_modules/runtime-tools/bin/runtime-qemu.js
runtime-tools@2.0.0 /usr/local/lib/node_modules/runtime-tools
├── minimist@1.2.0
├── shelljs@0.4.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── request@2.64.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.1.0, form-data@1.0.0-rc3, combined-stream@1.0.5, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@1.8.0)
└── nugget@1.5.4 (single-line-log@0.4.1, throttleit@0.0.2, debug@2.2.0, progress-stream@1.1.1, pretty-bytes@1.0.4)

$ runtime-qemu ./initrd
Downloading runtime-download-0.1.14
[============================================>] 100.0% of 9.22 MB (1.02 MB/s)
 --- starting qemu --- 
[INITRD] Load /bundle.js len 267729
v0.1.14 kernel (v8 4.5.107)
v0.1.25 core library
loading...
[random] using entropy source js-random
[UDP] no route to 8.8.8.8
Hello World!
```
